version: "3.10"
services:

  db:
    container_name: paycash_db
    image: postgres
    restart: always
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
      - 15432:5432

  main:
    container_name: paycash_app
    build: ./main
    restart: always
    env_file:
      - main.env
    ports:
      - 8000:8000
    depends_on:
      - db
